version: "3.8"
services:
  alpine-corretto-8:
    build:
      context: .
      dockerfile: alpine/8.alpine.Dockerfile
    image: ${REGISTRY_URL}amazoncorretto:8.alpine-${ARCH:-amd64}

  alpine-corretto-11:
    build:
      context: .
      dockerfile: alpine/11.alpine.Dockerfile
    image: ${REGISTRY_URL}amazoncorretto:11.alpine-${ARCH:-amd64}

  alpine-corretto-15:
    build:
      context: .
      dockerfile: alpine/15.alpine.Dockerfile
    image: ${REGISTRY_URL}amazoncorretto:15.alpine-${ARCH:-amd64}

  alpine-corretto-16:
    build:
      context: .
      dockerfile: alpine/16.alpine.Dockerfile
    image: ${REGISTRY_URL}amazoncorretto:16.alpine-${ARCH:-amd64}

  alpine-corretto-17:
    build:
      context: .
      dockerfile: alpine/17.alpine.Dockerfile
    image: ${REGISTRY_URL}amazoncorretto:17.alpine-${ARCH:-amd64}
