---
# Docker compose to streamline the images build

services:
  amzn2-corretto-8:
    build:
      context: .
      dockerfile: amzn2/8.amzn2.Dockerfile
    image: ${REGISTRY_URL}amazoncorretto:8.amzn2-${ARCH:-amd64}

  amzn2-corretto-11:
    build:
      context: .
      dockerfile: amzn2/11.amzn2.Dockerfile
    image: ${REGISTRY_URL}amazoncorretto:11.amzn2-${ARCH:-amd64}

  amzn2-corretto-15:
    build:
      context: .
      dockerfile: amzn2/15.amzn2.Dockerfile
    image: ${REGISTRY_URL}amazoncorretto:15.amzn2-${ARCH:-amd64}

  alpine-corretto-8:
    build:
      context: .
      dockerfile: alpine/8.alpine.Dockerfile
    image: ${REGISTRY_URL}amazoncorretto:8.alpine-${ARCH:-amd64}

  alpine-corretto-11:
    build:
      context: .
      dockerfile: alpine/11.alpine.Dockerfile
    image: ${REGISTRY_URL}amazoncorretto:11.alpine-${ARCH:-amd64}

  alpine-corretto-15:
    build:
      context: .
      dockerfile: alpine/15.alpine.Dockerfile
    image: ${REGISTRY_URL}amazoncorretto:15.alpine-${ARCH:-amd64}
